/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oddeven.h"


float
oddeven_6(char *host,float num)
{
	CLIENT *clnt;
	float  *result_1;
	float  check_6_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, oddeven, oddeven_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	check_6_arg= num;
	result_1 = check_6(&check_6_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *(result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	float number1;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	printf("Enter your number:\n");
    	scanf("%f",&number1);
	host = argv[1];
	float result5=  oddeven_6(host,number1);
	if(result5 == (float)0){
		printf("number %d  is Even\n",(int)number1);
	}
	else{
	printf("number %d  is ODD\n",(int) number1);
	}
	
	
exit (0);
}
