/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oddeven.h"

float *
check_6_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	
	result = (int) *(argp) % 2;
	
	
	return &result;
}
